# Generated by Django 4.2.3 on 2023-08-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_desc', models.TextField()),
                ('recipe_img', models.ImageField(upload_to='assets')),
            ],
        ),
    ]
