# Generated by Django 4.2.3 on 2023-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_reciepe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
